//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpiderDocsServer.WebReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebReference.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name clientID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Activation", ReplyAction="*")]
        SpiderDocsServer.WebReference.ActivationResponse Activation(SpiderDocsServer.WebReference.ActivationRequest request);
        
        // CODEGEN: Generating message contract since element name clientID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/checkUpdate", ReplyAction="*")]
        SpiderDocsServer.WebReference.checkUpdateResponse checkUpdate(SpiderDocsServer.WebReference.checkUpdateRequest request);
        
        // CODEGEN: Generating message contract since element name clientID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/downloadDone", ReplyAction="*")]
        SpiderDocsServer.WebReference.downloadDoneResponse downloadDone(SpiderDocsServer.WebReference.downloadDoneRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActivationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Activation", Namespace="http://tempuri.org/", Order=0)]
        public SpiderDocsServer.WebReference.ActivationRequestBody Body;
        
        public ActivationRequest() {
        }
        
        public ActivationRequest(SpiderDocsServer.WebReference.ActivationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActivationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string clientID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string productKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string currentVersion;
        
        public ActivationRequestBody() {
        }
        
        public ActivationRequestBody(string clientID, string productKey, string currentVersion) {
            this.clientID = clientID;
            this.productKey = productKey;
            this.currentVersion = currentVersion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActivationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActivationResponse", Namespace="http://tempuri.org/", Order=0)]
        public SpiderDocsServer.WebReference.ActivationResponseBody Body;
        
        public ActivationResponse() {
        }
        
        public ActivationResponse(SpiderDocsServer.WebReference.ActivationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActivationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ActivationResult;
        
        public ActivationResponseBody() {
        }
        
        public ActivationResponseBody(string ActivationResult) {
            this.ActivationResult = ActivationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkUpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkUpdate", Namespace="http://tempuri.org/", Order=0)]
        public SpiderDocsServer.WebReference.checkUpdateRequestBody Body;
        
        public checkUpdateRequest() {
        }
        
        public checkUpdateRequest(SpiderDocsServer.WebReference.checkUpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class checkUpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string clientID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string currentVersion;
        
        public checkUpdateRequestBody() {
        }
        
        public checkUpdateRequestBody(string clientID, string currentVersion) {
            this.clientID = clientID;
            this.currentVersion = currentVersion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkUpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkUpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public SpiderDocsServer.WebReference.checkUpdateResponseBody Body;
        
        public checkUpdateResponse() {
        }
        
        public checkUpdateResponse(SpiderDocsServer.WebReference.checkUpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class checkUpdateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string checkUpdateResult;
        
        public checkUpdateResponseBody() {
        }
        
        public checkUpdateResponseBody(string checkUpdateResult) {
            this.checkUpdateResult = checkUpdateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class downloadDoneRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="downloadDone", Namespace="http://tempuri.org/", Order=0)]
        public SpiderDocsServer.WebReference.downloadDoneRequestBody Body;
        
        public downloadDoneRequest() {
        }
        
        public downloadDoneRequest(SpiderDocsServer.WebReference.downloadDoneRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class downloadDoneRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string clientID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string currentVersion;
        
        public downloadDoneRequestBody() {
        }
        
        public downloadDoneRequestBody(string clientID, string currentVersion) {
            this.clientID = clientID;
            this.currentVersion = currentVersion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class downloadDoneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="downloadDoneResponse", Namespace="http://tempuri.org/", Order=0)]
        public SpiderDocsServer.WebReference.downloadDoneResponseBody Body;
        
        public downloadDoneResponse() {
        }
        
        public downloadDoneResponse(SpiderDocsServer.WebReference.downloadDoneResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class downloadDoneResponseBody {
        
        public downloadDoneResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : SpiderDocsServer.WebReference.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<SpiderDocsServer.WebReference.ServiceSoap>, SpiderDocsServer.WebReference.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SpiderDocsServer.WebReference.ActivationResponse SpiderDocsServer.WebReference.ServiceSoap.Activation(SpiderDocsServer.WebReference.ActivationRequest request) {
            return base.Channel.Activation(request);
        }
        
        public string Activation(string clientID, string productKey, string currentVersion) {
            SpiderDocsServer.WebReference.ActivationRequest inValue = new SpiderDocsServer.WebReference.ActivationRequest();
            inValue.Body = new SpiderDocsServer.WebReference.ActivationRequestBody();
            inValue.Body.clientID = clientID;
            inValue.Body.productKey = productKey;
            inValue.Body.currentVersion = currentVersion;
            SpiderDocsServer.WebReference.ActivationResponse retVal = ((SpiderDocsServer.WebReference.ServiceSoap)(this)).Activation(inValue);
            return retVal.Body.ActivationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SpiderDocsServer.WebReference.checkUpdateResponse SpiderDocsServer.WebReference.ServiceSoap.checkUpdate(SpiderDocsServer.WebReference.checkUpdateRequest request) {
            return base.Channel.checkUpdate(request);
        }
        
        public string checkUpdate(string clientID, string currentVersion) {
            SpiderDocsServer.WebReference.checkUpdateRequest inValue = new SpiderDocsServer.WebReference.checkUpdateRequest();
            inValue.Body = new SpiderDocsServer.WebReference.checkUpdateRequestBody();
            inValue.Body.clientID = clientID;
            inValue.Body.currentVersion = currentVersion;
            SpiderDocsServer.WebReference.checkUpdateResponse retVal = ((SpiderDocsServer.WebReference.ServiceSoap)(this)).checkUpdate(inValue);
            return retVal.Body.checkUpdateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SpiderDocsServer.WebReference.downloadDoneResponse SpiderDocsServer.WebReference.ServiceSoap.downloadDone(SpiderDocsServer.WebReference.downloadDoneRequest request) {
            return base.Channel.downloadDone(request);
        }
        
        public void downloadDone(string clientID, string currentVersion) {
            SpiderDocsServer.WebReference.downloadDoneRequest inValue = new SpiderDocsServer.WebReference.downloadDoneRequest();
            inValue.Body = new SpiderDocsServer.WebReference.downloadDoneRequestBody();
            inValue.Body.clientID = clientID;
            inValue.Body.currentVersion = currentVersion;
            SpiderDocsServer.WebReference.downloadDoneResponse retVal = ((SpiderDocsServer.WebReference.ServiceSoap)(this)).downloadDone(inValue);
        }
    }
}
